# Generated by Django 4.2.23 on 2025-06-30 21:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('NGO', 'Organizacja pozarządowa'), ('GOV', 'Instytucja publiczna')], max_length=3)),
                ('psychological_help', models.BooleanField(default=False)),
                ('social_help', models.BooleanField(default=False)),
                ('legal_help', models.BooleanField(default=False)),
                ('accommodation', models.BooleanField(default=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('description', models.TextField(blank=True, null=True)),
                ('opening_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, default=False, max_length=255, null=True)),
                ('infoline', models.CharField(blank=True, default=False, max_length=255, null=True)),
            ],
        ),
    ]
