# Generated by Django 4.2.23 on 2025-06-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='phone_number',
            field=models.CharField(max_length=200),
        ),
    ]
