# Generated by Django 5.2.2 on 2025-06-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
