# Generated by Django 5.2.2 on 2025-06-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0002_institution_opening_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='email',
            field=models.CharField(blank=True, default=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='infoline',
            field=models.CharField(blank=True, default=False, max_length=255, null=True),
        ),
    ]
