# Generated by Django 5.2.3 on 2025-06-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0003_institution_email_institution_infoline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
